## My Ansible automation script on installing httpd "open-source cross-platform web server software".

---
 -  name: Installing httpd
    hosts: localhost
    become: yes
    become_user: root
    tasks:
      - name: httpd install task
        yum:
          name: httpd
          state: present
      - name: ensure apache is running
        service:
          name: httpd
          state: started



#########################################################

## Notes:
  # name Name of the playbook

#  hosts A set of hosts usually grouped together as a host group and defined in inventory file

#  become To tell ansible this play has to be executed with elevated privileges

#  become_user the user name that we want to switch to like compare it with sudo su - user

#  tasks set of tasks to execute, All tasks would be defined below this

# and then we have two tasks with two modules, the first module is yum and the second module is service

# in the first task with yum  the state latest represents that the forementioned package httpd should be installed if it is not installed (or) if it is already installed it should be upgraded to the latest version available. If you do not want it to be upgraded if present, You can change it to state: present

# On the Second task with service module, we are making sure that the service named httpd is started and running using the state: started Ansible would not restart the service if it is already started and running.
